name: Update Letterboxd Films

on:
  # Esegui ogni domenica alle 3:00 AM UTC
  schedule:
    - cron: '0 3 * * 0'
  
  # Permetti esecuzione manuale
  workflow_dispatch:

jobs:
  update-films:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: 📦 Install dependencies
        run: npm ci
      
      - name: 🌐 Install Chromium for Puppeteer
        run: npx puppeteer browsers install chrome
      
      - name: 🎬 Run scraper and migration
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: npm run scrape
      
      - name: 🔍 Check for changes
        id: check_changes
        run: |
          if git diff --quiet current_10.json films-corti.json films-lunghi.json; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
          fi
      
      - name: 💾 Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add current_10.json films-corti.json films-lunghi.json
          git commit -m "🎬 Auto-update: Letterboxd films ($(date +'%Y-%m-%d %H:%M'))"
          git push
      
      - name: 📢 Notify Render (optional)
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          # Trigger Render reload endpoint (se configurato)
          # curl -X POST https://your-render-app.onrender.com/reload
          echo "✅ Update completed - Render will auto-reload on next request"
      
      - name: ℹ️ No changes
        if: steps.check_changes.outputs.changes == 'false'
        run: echo "No changes needed - current_10 films are still the same"